### ISSUE TITLE
Should we switch Netty to use the Java SSL engine instead of tcnative/boringssl?

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-beats#188]
Everything else in Logstash uses Java crypto (and sometimes bouncycastle, but that's still java). This input is an exception that it uses libssl (via tcnative/boringssl).

I'd like to consider moving to have this input use Java crypto instead of boringssl.

Thoughts?

**Comment by ph** [comment]
@jordansissel For compatibility reason, We should move to it. I don't expect it to be really hard, all the SSL logic is encapsulated in one classes.

**Comment by jasperla** [comment]
As mentioned in #174 this would unbreak logstash-input-beats on (at least) OpenBSD and make it properly cross-platform. Is there any progress on this issue?

**Comment by jordansissel** [comment]
jasper, I recommend you follow this ticket to get updates on this issue.

**Comment by jasperla** [comment]
Will do; if there's anything I could help out with I'd be happy to get a few pointers.. ;-)

**Comment by buzzdeee** [comment]
ES/Kibana 5.3 seems to be all fine on OpenBSD, just gave LS a shot, but still stuck here with 2.4 :(

**Comment by dlangille** [comment]
Also getting stuck on FreeBSD with this same exact issue.

SSL ALL THE THINGS!

**Comment by jordansissel** [comment]
I'll see what we can do this week or next.

**Comment by dlangille** [comment]
Very happy to test anything you can supply in the meantime.

**Comment by jordansissel** [comment]
In terms of code, the steps are roughly:

* Tell Netty to use Java crypto instead of OpenSSL (this is some API calls)
* Write tests to verify the new behavior (if possible, I haven't checked the API)
* Make sure the test suite passes

**Comment by original-brownbear** [comment]
@jordansissel working on https://github.com/logstash-plugins/logstash-input-tcp/issues/7 I came across this warning http://netty.io/wiki/requirements-for-4.x.html#jdk-ciphers.

I think for the many connection use case in TCP this matters measurably, but I can't judge if this type of performance hit is a problem for this plugin as well? Maybe we shouldn't indiscriminately switch to the Java crypto backend and make this a setting instead?

**Comment by jakelandis** [comment]
Also, when switching Java crypto backend, assuming is going through the JCE interface _(e.g. not directly against an implementation)_ then deployers will need to be have the [Unlimited Strength Jurisdiction Policy Files](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) installed, which at least in my experience has been a deployment pain point _(humans tend to forget this)_ without 3rd party configuration management. 

I believe this maybe another reason to opt for making this a setting. 

Also see: http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#importlimits

**Comment by original-brownbear** [comment]
@jakelandis yea  +1000 on the import/export restrictions being a huge issue as well.
After having sunk a bunch of time into this at least to me it looks like the Netty OpenSSL is the most standard conforming + portable version.
I'd make this the default and simply make the fallback to a Java SSL version a setting so that other *nix that aren't compatible right now will be compatible?

**Comment by jordansissel** [comment]
> deployers will need to be have the Unlimited Strength Jurisdiction Policy Files installed

This is only true if you use Oracle JRE. OpenJDK, I think, defaults to this "unlimited strength" scenario.

> yea +1000 on the import/export restrictions being a huge issue as well

I'm not a lawyer familiar with various export restrictions laws, so I don't have anything to add or remove here beyond suggesting that it's been a while since I've heard of encryption export being a problem.

If forgetfulness is a problem, we can detect this scenario to notify users about this forgotten step.

We document this scenario for Elasticsearch X-Pack users: https://www.elastic.co/guide/en/x-pack/current/ciphers.html

> I believe this maybe another reason to opt for making this a setting.

I don't believe this should be a setting. If you want to support everything, then we can have this decision tree:

* Try tcnative
* If tcnative fails, use Java crypto

* If java crypto is missing strong ciphers, and the user is using Oracle Java, and the user has selected a cipher that would be provided by Oracle's "unlimited strength" policy ceremony, then we should notify the user with an error and fail to start.

**Comment by original-brownbear** [comment]
@jordansissel 

> This is only true if you use Oracle JRE. OpenJDK, I think, defaults to this "unlimited strength" scenario.

In the world of enterprise setups, Oracle is all over the place, especially in Europe and def. hit by the export restrictions.

> I don't believe this should be a setting. If you want to support everything, then we can have this decision tree

We can do that too and I guess we all like it better, aside from taking longer to implement I see no downsides :)

**Comment by jordansissel** [comment]
@original-brownbear I suppose my suggestion is that if a user is impacted by export restrictions, working around this by using open source implementations of those import-restricted crypto systems seems like asking for legal trouble (or worse?)?

**Comment by original-brownbear** [comment]
@jordansissel 

> asking for legal trouble (or worse?)

Hmm, interesting question ... I have no idea how transitive dependencies are counted here, but intuitively (not that that's worth much when it comes to legal) I agree, this seems like it's not gonna fly :(

**Comment by jordansissel** [comment]
Noting this issue came up again today with a customer where tcnative could not be loaded.

**Comment by mstaudinger** [comment]
Another FreeBSD user here - eager to implement Elastic 5.X but unable to do so until filebeat can speak TLS to logstash.  Also willing to test any changes to this pipeline.

**Comment by steffenfritz** [comment]
Another FreeBSD user here, unable to work with filebeat and logstash.

**Comment by Dhyrule** [comment]
Same issue on FreeBSD

**Comment by praseodym** [comment]
Netty without tcnative uses Java's default AES-GCM implementation, which is [terribily slow (<20MB/s) on the Java 8 JVM](https://stackoverflow.com/questions/35175813/aes-gcm-with-hardware-accelerated-support-before-java-9). Because [AES-GCM ciphers are currently default](https://github.com/logstash-plugins/logstash-input-beats/blob/b5a714916eaa9ed6ab7c2a2efab167a298b6af19/src/main/java/org/logstash/netty/SslSimpleBuilder.java#L47-L56) this would have a significant performance impact.

A way forward could be to make tcnative optional by using the JVM's native implementation only as a fallback. Also, it could be that a newer version of netty-tcnative (#279) has some compatibility advantages, but since there are no proper release notes I cannot confirm this (there are some [compatibility-related commits](https://github.com/netty/netty-tcnative/commits/master) though).

**Comment by sadsfae** [comment]
Currently have this issue as well on CentOS7.4 / RHEL7.4.
I'm trying to update my Ansible playbook to support 6.2 and have employed this in ```/etc/logstash/jvm.options`` to no avail after creating another directory with 777 perms for testing

```
-Dio.netty.native.workdir=/usr/share/logstash/tmpfile
```

Still get the same issue:
```
[2018-02-21T19:21:43,100][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-02-21T19:21:43,107][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"<LogStash::Inputs::Beats port=>5044, ssl=>true, ssl_certificate=>\"/usr/share/logstash/beat-forwarder.crt\", ssl_key=>\"/usr/share/logstash/beat-forwarder.key\", ssl_verify_mode=>\"none\", id=>\"e67fbdeee36e267df3899a867a5a61aad7796de7860b838baef838f4949d6090\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_44e88ded-720c-499b-b9a8-d4717200ec30\", enable_metric=>true, charset=>\"UTF-8\">, host=>\"0.0.0.0\", include_codec_tag=>true, ssl_handshake_timeout=>10000, tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>[\"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\", \"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256\", \"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256\"], client_inactivity_timeout=>60, executor_threads=>16>", :error=>"Cipher `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` is not available", :thread=>"#<Thread:0x22a035a1@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246 run>"}
```

Version:  logstash-6.2.2-1.noarch

**Comment by praseodym** [comment]
@sadsfae what JVM version are you running Logstash on?

**Comment by sadsfae** [comment]
Hey @praseodym I'm running ```java-1.8.0-openjdk-headless-1.8.0.161-0.b14.el7_4.x86_64```

I found a netty permission issue here that led me to changing ```netty.native.workdir``` by the way:

https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841/5

**Comment by praseodym** [comment]
That should work. Could you start Logstash with `--debug` and provide us with the output?

Two more things I'd check would be:
- Are the certificate files in the form that Netty expects?
- Does your JVM have 'unlimited crypto' enabled? This should be the case for all current official JVM versions, but I'm not sure about distro-built packages.

**Comment by sadsfae** [comment]
Hey @praseodym here are my debug logs:

https://paste.fedoraproject.org/paste/AHCk2fsATOO36AjgVB81PA

The certificate file is in a ```.crt``` format and works fine with prior versions of logstash, here is openssl output:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            93:69:be:b8:34:b8:67:6e
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=TG, ST=Togo, L=Lome, O=Private company, CN=*
        Validity
            Not Before: Feb 21 19:12:14 2018 GMT
            Not After : Feb 19 19:12:14 2028 GMT
        Subject: C=TG, ST=Togo, L=Lome, O=Private company, CN=*
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:bd:df:ef:9a:c9:35:64:63:fc:a5:c3:60:93:8b:
                    a0:c6:31:ee:1c:de:29:ec:34:20:56:e9:a3:63:86:
                    43:55:86:1a:93:76:6f:38:7f:53:1e:f8:9a:7f:84:
                    86:14:45:41:47:fb:36:08:b8:99:3b:80:f5:29:97:
                    f5:a1:83:d3:19:8b:c1:6e:5a:24:31:73:66:d3:26:
                    27:37:fb:74:22:fb:5d:98:9a:1e:e7:96:c6:5a:79:
                    83:76:ba:3f:52:ba:f5:8c:a9:0d:9e:21:b1:fe:a9:
                    cc:7c:de:73:9d:7f:a6:41:b4:dd:78:d4:b9:a6:1a:
                    1d:d0:d9:be:1e:3a:7c:09:08:8e:4c:3d:60:be:fa:
                    85:36:a6:24:dc:5a:3a:48:04:09:1a:cb:e5:41:dd:
                    81:23:0d:b7:bf:0a:52:8c:08:42:69:e3:31:bf:97:
                    1c:20:ae:ed:e1:d3:fa:ba:09:ac:d8:65:74:fe:57:
                    74:4b:80:ba:41:98:7c:03:2f:54:03:cd:1a:99:61:
                    0d:fa:1e:01:c1:7f:a6:6d:03:c4:87:34:05:ad:4f:
                    cd:5e:e0:26:eb:fc:d6:cc:a0:b2:13:91:0b:53:c5:
                    79:75:db:19:04:91:af:c5:37:d7:f9:03:89:c5:a3:
                    33:a2:0b:ee:62:f6:e1:60:21:1f:cd:20:11:e8:cd:
                    71:c7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                B1:53:24:C4:AE:31:DC:60:33:FB:6D:55:32:19:F5:E1:F5:80:D1:90
            X509v3 Authority Key Identifier: 
                keyid:B1:53:24:C4:AE:31:DC:60:33:FB:6D:55:32:19:F5:E1:F5:80:D1:90

            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Alternative Name: 
                DNS:*, DNS:*.*, DNS:*.*.*, DNS:*.*.*.*, DNS:*.*.*.*.*, DNS:*.*.*.*.*.*, DNS:*.*.*.*.*.*.*, IP Address:192.168.122.81
    Signature Algorithm: sha256WithRSAEncryption
         a2:2a:c2:79:ca:b9:13:13:63:27:d2:25:f6:d9:74:81:c5:9c:
         eb:c6:18:7b:84:59:ef:c3:40:a2:9b:c4:95:e7:cd:d7:1f:4c:
         6e:d1:15:57:45:c2:16:49:0b:b3:c9:25:b4:04:f9:c2:bf:1a:
         6d:42:15:c2:52:03:54:31:95:a7:cd:d4:40:d4:aa:99:bd:3f:
         2c:93:33:b6:1a:5f:74:08:25:6b:69:f9:82:45:79:ca:72:98:
         03:a4:17:f9:e4:f4:97:5d:7b:65:5f:98:37:92:fe:3e:c3:28:
         cd:0f:f6:0f:de:41:d9:89:f4:23:1b:2e:f7:0b:7f:e0:be:36:
         5c:b9:ec:af:33:65:28:1d:fc:6b:25:18:f3:6d:37:11:5a:41:
         57:0c:ef:df:2b:ce:4c:48:7d:59:6f:9c:8b:e1:fc:d5:de:70:
         68:a5:22:53:e3:74:48:29:b3:26:6a:f5:57:14:30:ee:cf:f1:
         65:81:2a:9a:9f:16:00:0e:e3:e8:a1:c3:63:1d:14:06:e1:67:
         d5:54:91:ef:88:9c:9d:f5:43:8d:bb:ab:8e:b1:03:44:9c:47:
         68:2f:ae:dc:43:d1:9b:38:57:5c:53:38:18:8c:cc:d8:db:3f:
         e6:05:6d:13:13:fa:f3:70:ab:ee:7f:46:2d:1e:1f:ab:e8:29:
         ec:67:89:7a
-----BEGIN CERTIFICATE-----
MIIDxzCCAq+gAwIBAgIJAJNpvrg0uGduMA0GCSqGSIb3DQEBCwUAMFExCzAJBgNV
BAYTAlRHMQ0wCwYDVQQIDARUb2dvMQ0wCwYDVQQHDARMb21lMRgwFgYDVQQKDA9Q
cml2YXRlIGNvbXBhbnkxCjAIBgNVBAMMASowHhcNMTgwMjIxMTkxMjE0WhcNMjgw
MjE5MTkxMjE0WjBRMQswCQYDVQQGEwJURzENMAsGA1UECAwEVG9nbzENMAsGA1UE
BwwETG9tZTEYMBYGA1UECgwPUHJpdmF0ZSBjb21wYW55MQowCAYDVQQDDAEqMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvd/vmsk1ZGP8pcNgk4ugxjHu
HN4p7DQgVumjY4ZDVYYak3ZvOH9THviaf4SGFEVBR/s2CLiZO4D1KZf1oYPTGYvB
blokMXNm0yYnN/t0IvtdmJoe55bGWnmDdro/Urr1jKkNniGx/qnMfN5znX+mQbTd
eNS5phod0Nm+Hjp8CQiOTD1gvvqFNqYk3Fo6SAQJGsvlQd2BIw23vwpSjAhCaeMx
v5ccIK7t4dP6ugms2GV0/ld0S4C6QZh8Ay9UA80amWEN+h4BwX+mbQPEhzQFrU/N
XuAm6/zWzKCyE5ELU8V5ddsZBJGvxTfX+QOJxaMzogvuYvbhYCEfzSAR6M1xxwID
AQABo4GhMIGeMB0GA1UdDgQWBBSxUyTErjHcYDP7bVUyGfXh9YDRkDAfBgNVHSME
GDAWgBSxUyTErjHcYDP7bVUyGfXh9YDRkDAMBgNVHRMEBTADAQH/ME4GA1UdEQRH
MEWCASqCAyouKoIFKi4qLiqCByouKi4qLiqCCSouKi4qLiouKoILKi4qLiouKi4q
LiqCDSouKi4qLiouKi4qLiqHBMCoelEwDQYJKoZIhvcNAQELBQADggEBAKIqwnnK
uRMTYyfSJfbZdIHFnOvGGHuEWe/DQKKbxJXnzdcfTG7RFVdFwhZJC7PJJbQE+cK/
Gm1CFcJSA1QxlafN1EDUqpm9PyyTM7YaX3QIJWtp+YJFecpymAOkF/nk9Jdde2Vf
mDeS/j7DKM0P9g/eQdmJ9CMbLvcLf+C+Nly57K8zZSgd/GslGPNtNxFaQVcM798r
zkxIfVlvnIvh/NXecGilIlPjdEgpsyZq9VcUMO7P8WWBKpqfFgAO4+ihw2MdFAbh
Z9VUke+InJ31Q427q46xA0ScR2gvrtxD0Zs4V1xTOBiMzNjbP+YFbRMT+vNwq+5/
Ri0eH6voKexniXo=
-----END CERTIFICATE-----
```

So far as JVM this is output of ```java -verbose``` is here but I'm not sure that's what you are looking for to see if unlimited crypto is compiled or not, it's just a standard distribution package:

https://paste.fedoraproject.org/paste/7O7hqlNVEYIIMrFPQ0gw1w

**Comment by sadsfae** [comment]
This seems related: https://github.com/elastic/logstash-docker/issues/77

**Comment by praseodym** [comment]
This line gives a hint on what’s wrong:
```
[2018-02-21T19:55:36,126][DEBUG][io.netty.handler.ssl.OpenSsl] netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
```
I’m not yet sure what causes this.

Also, ignore my comment about unlimited crypto; it doesn’t matter as Netty should be using tcnative instead of JCE.

**Comment by sadsfae** [comment]
@praseodym I'm digging around for the right options to do this via any ```/usr/share/logstash/bin/logstash``` documentation but if you know them offhand please reply - will save some time.

**Comment by praseodym** [comment]
The `Unable to load the library 'netty_tcnative_linux_x86_64', trying other loading mechanism` message you're seeing is not the problem: there is a `Successfully loaded the library` message later in the log (#288).

That everything is working normally when you have only the Beats input loaded [supports my earlier hypothesis](https://github.com/logstash-plugins/logstash-input-beats/issues/188#issuecomment-367465839) that the problem is a Netty classpath version conflict with the TCP input plugin (the UDP input plugin doesn't use Netty). I'd suggest you open an issue in the [logstash-input-tcp repository](https://github.com/logstash-plugins/logstash-input-tcp/issues); my proposed fix would be to upgrade Netty to the same version in that plugin, so that there is no longer a conflict.

**Comment by sadsfae** [comment]
@praseodym thank you for taking the time to look at this, I'll file an issue with logstash-input-tcp repository as you suggest.

**Comment by zBurrito** [comment]
Fixed in the logstash-input-tcp plugin:
https://github.com/logstash-plugins/logstash-input-tcp/pull/113

**Comment by buzzdeee** [comment]
The issue is still not solved for me on OpenBSD. Just tried logstash 6.2.4 but to no avail. Still get:

```
[2018-05-03T15:23:39,539][DEBUG][io.netty.handler.ssl.CipherSuiteConverter] Cipher suite mapping: TLS_RSA_WITH_AES_256_CBC_SHA => AES256-SHA
[2018-05-03T15:23:39,667][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"filebeat", :plugin=>"<LogStash::Inputs::Beats host=>\"127.0.0.1\", port=>12364, ssl=>true, ssl_certificate=>\"/etc/logstash/logstash.crt\", ssl_key=>\"/etc/logstash/logstash.k
ey\", ssl_certificate_authorities=>[\"/etc/logstash/logstash-ca.crt\"], ssl_verify_mode=>\"force_peer\", cipher_suites=>[\"TLS_RSA_WITH_AES_256_CBC_SHA\"], id=>\"17bc8358fd2c70b96be88770c5e9688af36df9092a9cf01fba9d65923ee0aa8a\", enable_metric=>true, codec=><LogStash::Codecs:
:Plain id=>\"plain_9708949a-98b9-4662-ba6c-05d4cd4cd765\", enable_metric=>true, charset=>\"UTF-8\">, include_codec_tag=>true, ssl_handshake_timeout=>10000, tls_min_version=>1, tls_max_version=>1.2, client_inactivity_timeout=>60, executor_threads=>1>", :error=>"Cipher `TLS_RSA
_WITH_AES_256_CBC_SHA` is not available", :thread=>"#<Thread:0x6be5c673 run>"}
```

looking at the netty-tcnative-boringssl-static-2.0.7.Final.jar, there is still no libnetty_tcnative_openbsd_x86_64.so inside.
```

grep -i netty /tmp/ls_output.txt                                                                                                                                                                                                                                     
[2018-05-03T15:23:37,926][DEBUG][io.netty.util.internal.logging.InternalLoggerFactory] Using SLF4J as the default logging framework
[2018-05-03T15:23:38,216][DEBUG][io.netty.util.internal.PlatformDependent0] -Dio.netty.noUnsafe: false
[2018-05-03T15:23:38,218][DEBUG][io.netty.util.internal.PlatformDependent0] Java version: 8
[2018-05-03T15:23:38,229][DEBUG][io.netty.util.internal.PlatformDependent0] sun.misc.Unsafe.theUnsafe: available
[2018-05-03T15:23:38,235][DEBUG][io.netty.util.internal.PlatformDependent0] sun.misc.Unsafe.copyMemory: available
[2018-05-03T15:23:38,240][DEBUG][io.netty.util.internal.PlatformDependent0] java.nio.Buffer.address: available
[2018-05-03T15:23:38,245][DEBUG][io.netty.util.internal.PlatformDependent0] direct buffer constructor: available
[2018-05-03T15:23:38,256][DEBUG][io.netty.util.internal.PlatformDependent0] java.nio.Bits.unaligned: available, true
[2018-05-03T15:23:38,256][DEBUG][io.netty.util.internal.PlatformDependent0] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
[2018-05-03T15:23:38,256][DEBUG][io.netty.util.internal.PlatformDependent0] java.nio.DirectByteBuffer.<init>(long, int): available
[2018-05-03T15:23:38,257][DEBUG][io.netty.util.internal.PlatformDependent] sun.misc.Unsafe: available
[2018-05-03T15:23:38,260][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[2018-05-03T15:23:38,261][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.bitMode: 64 (sun.arch.data.model)
[2018-05-03T15:23:38,287][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.noPreferDirect: false
[2018-05-03T15:23:38,288][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.maxDirectMemory: 1065025536 bytes
[2018-05-03T15:23:38,288][DEBUG][io.netty.util.internal.PlatformDependent] -Dio.netty.uninitializedArrayAllocationThreshold: -1
[2018-05-03T15:23:38,304][DEBUG][io.netty.util.internal.CleanerJava6] java.nio.ByteBuffer.cleaner(): available
[2018-05-03T15:23:38,320][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.native.workdir: /usr/local/share/logstash/tmp
[2018-05-03T15:23:38,331][DEBUG][io.netty.util.internal.NativeLibraryLoader] Unable to load the library 'netty_tcnative_openbsd_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_tcnative_openbsd_x86_64 in java.library.path
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:421) [netty-all-4.1.18.Final.jar:4.1.18.Final]
...
```

**Comment by praseodym** [comment]
[tcnative doesn’t seem to support OpenBSD](https://netty.io/wiki/forked-tomcat-native.html) and [Logstash (officially) doesn’t either](https://www.elastic.co/support/matrix).

I think this can still be fixed by adding a fallback codepath for when the native library cannot be used. The main difference (IIRC) is that cipher suites are named differently in the JVM built-in crypto library.

**Comment by kifj** [comment]
Run into the same issue on Fedora 30 and openjdk-11, but with a different cause. For documentation purposes:
Failure to load the library 'netty_tcnative_linux_x86_64' was caused by missing libcrypto.so.1 (which was stated in the DEBUG log, but hard to find). 
Installing the package providing the dependency solved the issue (in Fedora 30 this is libxcrypt-compat)

**Comment by kares** [comment]
the plugin dropped BoringSSL in favor of using pure Java SSL in version 6.0.11
